<?php
/** @file
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Implements hook_form_alter().
 */
function appointmentvalid_form_alter(&$form, &$form_state, $form_id) {
 //dpm($form_id);
 if ($form_id == 'appointment_node_form') {
   $form['field_message'] = array(
     '#type' => 'item',
     '#title' => t('New article/appointment (PBC)'),
     '#markup' => t('You are about to create a new appointment (PBC)'),
     '#weight' => -6,
   );
   $form["#validate"][] = 'appointmentvalid_form_validate';
  }
}
/**
 * EFQ testing.
 * @TODO: https://www.drupal.org/node/1343708
 * Helper function to return if an appointment exists in the database
 * on a given time for a given doctor id
 */
function appointment_get($time, $doctor_id) {
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')
            ->entityCondition('bundle', 'appointment')
            ->propertyCondition('status', 1)
            ->fieldCondition('field_appointment_date', 'value', $time, '=')
            ->fieldCondition('field_appointment_doctor','target_id', $doctor_id, '=')
            ->range(0, 1); // Limit 1 ???
      $result = $query->execute();
      
      if (isset($result['node'])) {
        
             $nodes_nids = array_keys($result['node']);
             $nodes_items = entity_load('node', $nodes_nids); 
             return $nodes_nids[0];
      }
      
     return FALSE;
}

function appointmentvalid_form_validate($form, &$form_state) {
  
    $input_time_value = $form_state['values']['field_appointment_date']['und']['0']['value']; // Input-ul de Time Value din form
    $input_doctor_id = $form_state['values']['field_appointment_doctor']['und']['0']['target_id']; //Input-ul de Doctor din form
    $db_existing_value = $input_time_value;
    $doctor_id = $input_doctor_id;
    
   $existing_appointment = appointment_get($db_existing_value, $doctor_id);
   if ($existing_appointment != FALSE) {
     
     form_set_error('field_appointment_date', t('Please check the form and the data you inputed !!!'));
     
   }
}




//form_set_error('field_appointment_date', t('The node id that allready exist for that input is : ' . $existing_node['0']));
//  dpm('There ALREADY is an appointment on that date/hour for doctor with ID : ' . $doctor_id);

//@todo: studdy https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7#element_validate

///**
// * SQL db_select testing.
// * Helper function to return if an appointment exists in the database
// * on a given time for a given user id
// */
//function _appointment_exists_sql($time, $doctor_id) {
//will// return $node / FALSE.
//}

// table name : field_data_field_appointment_date = TABEL NAME
// field name : field_appointment_date_value   =  FIELD VALUE
// entity id  : entity_id = CHEIE COMUNA (cred)

// table name : field_data_field_appointment_doctor = TABEL NAME2
// field name : field_appointment_doctor_target_id = VALUE (id DOCTOR)
// entity id  : entity_id = CHEIE COMUNA (cred)